services:
  eshopwebmvc:
    image: 093215643118.dkr.ecr.us-east-1.amazonaws.com/eshoppublicapi:latest
    build:
      context: .
      dockerfile: src/Web/Dockerfile
  eshoppublicapi:
    image: 093215643118.dkr.ecr.us-east-1.amazonaws.com/eshoppublicapi:latest
    build:
      context: .
      dockerfile: src/PublicApi/Dockerfile
